/**
 * Downloads the typefaces used by this website and stores them locally under
 * assets/fonts/ so that the site makes no third-party requests (privacy /
 * DPDP friendly, faster first paint, works offline).
 *
 * Both families are licensed under the SIL Open Font License 1.1, which
 * permits self-hosting. The licence text is stored next to the font files.
 *
 * Run:  node tools/fetch-fonts.mjs
 * This is a one-off developer task - it is NOT required to run the website.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT_DIR = join(ROOT, 'assets', 'fonts');

const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36';

const SOURCES = [
  {
    family: 'Inter',
    css: 'https://fonts.googleapis.com/css2?family=Inter:wght@400;600&display=swap',
    licence: 'https://raw.githubusercontent.com/google/fonts/main/ofl/inter/OFL.txt',
    licenceFile: 'OFL-Inter.txt'
  },
  {
    family: 'Lora',
    css: 'https://fonts.googleapis.com/css2?family=Lora:wght@400;600&display=swap',
    licence: 'https://raw.githubusercontent.com/google/fonts/main/ofl/lora/OFL.txt',
    licenceFile: 'OFL-Lora.txt'
  }
];

/** Keep only the basic-latin subset: smallest payload, covers this site's text. */
const isLatinSubset = (block) => /unicode-range:\s*U\+0000-00FF/i.test(block);

const slug = (value) => value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');

async function fetchText(url) {
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`GET ${url} -> ${res.status} ${res.statusText}`);
  return res.text();
}

async function fetchBinary(url) {
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`GET ${url} -> ${res.status} ${res.statusText}`);
  return Buffer.from(await res.arrayBuffer());
}

async function main() {
  await mkdir(OUT_DIR, { recursive: true });

  const localFaceBlocks = [];

  for (const source of SOURCES) {
    const css = await fetchText(source.css);
    const blocks = css.match(/@font-face\s*\{[^}]*\}/g) ?? [];
    const latinBlocks = blocks.filter(isLatinSubset);

    if (!latinBlocks.length) {
      throw new Error(`No latin @font-face blocks returned for ${source.family}`);
    }

    for (const block of latinBlocks) {
      const weight = /font-weight:\s*(\d+)/.exec(block)?.[1] ?? '400';
      const style = /font-style:\s*(normal|italic)/.exec(block)?.[1] ?? 'normal';
      const url = /url\((https:[^)]+\.woff2)\)/.exec(block)?.[1];
      if (!url) continue;

      const file = `${slug(source.family)}-${weight}${style === 'italic' ? '-italic' : ''}.woff2`;
      const bytes = await fetchBinary(url);
      await writeFile(join(OUT_DIR, file), bytes);
      console.log(`saved assets/fonts/${file} (${(bytes.length / 1024).toFixed(1)} kB)`);

      localFaceBlocks.push(
        [
          '@font-face {',
          `  font-family: '${source.family}';`,
          `  font-style: ${style};`,
          `  font-weight: ${weight};`,
          '  font-display: swap;',
          `  src: url('../fonts/${file}') format('woff2');`,
          '  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA,',
          '    U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193,',
          '    U+2212, U+2215, U+FEFF, U+FFFD;',
          '}'
        ].join('\n')
      );
    }

    try {
      const licence = await fetchText(source.licence);
      await writeFile(join(OUT_DIR, source.licenceFile), licence, 'utf8');
      console.log(`saved assets/fonts/${source.licenceFile}`);
    } catch (error) {
      console.warn(`Could not download licence text for ${source.family}: ${error.message}`);
    }
  }

  const header = [
    '/* ------------------------------------------------------------------------',
    '   SELF-HOSTED TYPEFACES - generated by tools/fetch-fonts.mjs',
    '   Inter and Lora are licensed under the SIL Open Font License 1.1.',
    '   Licence texts: assets/fonts/OFL-Inter.txt, assets/fonts/OFL-Lora.txt',
    '   Do not swap these files for commercial fonts without a valid licence.',
    '   ------------------------------------------------------------------------ */',
    ''
  ].join('\n');

  await writeFile(join(OUT_DIR, 'fonts.css'), header + localFaceBlocks.join('\n\n') + '\n', 'utf8');
  console.log('saved assets/fonts/fonts.css');
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
